// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo9jvssVmAAP5UIBb44VNoNjPMzKt0FDw',
    appId: '1:392360097024:web:5fcf681d0fbf90ad892fe5',
    messagingSenderId: '392360097024',
    projectId: 'gsheets-338919',
    authDomain: 'gsheets-338919.firebaseapp.com',
    storageBucket: 'gsheets-338919.appspot.com',
    measurementId: 'G-3WFFEQLBD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASpjxcKP95BUidhnrhh7xM1sPKwpXvnQw',
    appId: '1:392360097024:android:adc4690b5c3a03bc892fe5',
    messagingSenderId: '392360097024',
    projectId: 'gsheets-338919',
    storageBucket: 'gsheets-338919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkZmMXpiEZgsYomegg1UwgBF9FzqD3gIM',
    appId: '1:392360097024:ios:3a8e4c2270cc4092892fe5',
    messagingSenderId: '392360097024',
    projectId: 'gsheets-338919',
    storageBucket: 'gsheets-338919.appspot.com',
    iosClientId: '392360097024-n83545ffhkoe0qc1t107eipru5hrimlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.runFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkZmMXpiEZgsYomegg1UwgBF9FzqD3gIM',
    appId: '1:392360097024:ios:3a8e4c2270cc4092892fe5',
    messagingSenderId: '392360097024',
    projectId: 'gsheets-338919',
    storageBucket: 'gsheets-338919.appspot.com',
    iosClientId: '392360097024-n83545ffhkoe0qc1t107eipru5hrimlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.runFinder',
  );
}
